/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.cafe.ui;

import poly.cafe.ui.manager.CategoryManagerJDialog;
import poly.cafe.util.GlobalState;

/**
 *
 * @author Admin
 */
public class PolyCafeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PolyCafeJFrame
     */
    public PolyCafeJFrame() {
        initComponents();
        // Khi mở cửa sổ PolyCafeJFrame 
        // -> Hiển thị cửa sổ đăng nhập LoginJDialog
        // Nghĩa là: từ màn hình này gọi đến màn hình khác
        LoginJDialog loginJDialog = new LoginJDialog(this, true); 
        loginJDialog.setVisible(true);
        
        
        // Phân quyền xem các nút 
        // Nhân viên: Ẩn 6 nút trong ảnh
        if (GlobalState.Manager == false) {
            btnDoUong.setVisible(false);
            btnLoaiDoUong.setVisible(false);
            btnTheDinhDanh.setVisible(false);
            btnPhieuBanHang.setVisible(false);
            btnNguoiSuDung.setVisible(false);
            btnDoanhThu.setVisible(false);
        }
        
        // Hiện tên user đăng nhập
        txtFullname.setText(GlobalState.Fullname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtFullname = new javax.swing.JTextField();
        btnBanHang = new javax.swing.JButton();
        btnLichSu = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        btnDoUong = new javax.swing.JButton();
        btnPhieuBanHang = new javax.swing.JButton();
        btnLoaiDoUong = new javax.swing.JButton();
        btnNguoiSuDung = new javax.swing.JButton();
        btnTheDinhDanh = new javax.swing.JButton();
        btnDoanhThu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\PolyCafe\\src\\main\\resources\\icons\\trump-small.png")); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 66, 118, 179));
        getContentPane().add(txtFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 263, -1, -1));

        btnBanHang.setText("BÁN HÀNG");
        getContentPane().add(btnBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 374, 110, 49));

        btnLichSu.setText("LỊCH SỬ");
        getContentPane().add(btnLichSu, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 374, 108, 49));

        btnDoiMatKhau.setText("ĐỔI MẬT KHẨU");
        getContentPane().add(btnDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 502, -1, 45));

        btnKetThuc.setText("KẾT THÚC");
        getContentPane().add(btnKetThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 502, 108, 46));

        btnDoUong.setText("ĐỒ UỐNG");
        getContentPane().add(btnDoUong, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 140, 50));

        btnPhieuBanHang.setText("PHIẾU BÁN HÀNG");
        getContentPane().add(btnPhieuBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 140, 50));

        btnLoaiDoUong.setText("LOẠI ĐỒ UỐNG");
        btnLoaiDoUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiDoUongActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoaiDoUong, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 140, 50));

        btnNguoiSuDung.setText("NGƯỜI SỬ DỤNG");
        getContentPane().add(btnNguoiSuDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 140, 50));

        btnTheDinhDanh.setText("THẺ ĐỊNH DANH");
        getContentPane().add(btnTheDinhDanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 140, 50));

        btnDoanhThu.setText("DOANH THU");
        getContentPane().add(btnDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 140, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\PolyCafe\\src\\main\\resources\\icons\\coffee-shop.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 730, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoaiDoUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiDoUongActionPerformed
        // TODO add your handling code here:
        // Nhảy sang màn hình Quản lý Loại đồ uống
        CategoryManagerJDialog categoryManagerJDialog = new CategoryManagerJDialog(this, true); 
        categoryManagerJDialog.setVisible(true);
    }//GEN-LAST:event_btnLoaiDoUongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolyCafeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnDoUong;
    private javax.swing.JButton btnDoanhThu;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnLichSu;
    private javax.swing.JButton btnLoaiDoUong;
    private javax.swing.JButton btnNguoiSuDung;
    private javax.swing.JButton btnPhieuBanHang;
    private javax.swing.JButton btnTheDinhDanh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtFullname;
    // End of variables declaration//GEN-END:variables
}
