/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.cafe.ui;

/**
 *
 * @author Admin
 */
public class PolyCafeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PolyCafeJFrame
     */
    public PolyCafeJFrame() {
        initComponents();
        // Khi mở cửa sổ PolyCafeJFrame 
        // -> Hiển thị cửa sổ đăng nhập LoginJDialog
        // Nghĩa là: từ màn hình này gọi đến màn hình khác
        LoginJDialog loginJDialog = new LoginJDialog(this, true); 
        loginJDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\PolyCafe\\src\\main\\resources\\icons\\trump-small.png")); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 66, 118, 179));

        jTextField1.setText("Nguyễn Văn User 1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 263, -1, -1));

        jButton2.setText("BÁN HÀNG");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 374, 110, 49));

        jButton3.setText("LỊCH SỬ");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 374, 108, 49));

        jButton4.setText("ĐỔI MẬT KHẨU");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 502, -1, 45));

        jButton5.setText("KẾT THÚC");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 502, 108, 46));

        jButton6.setText("ĐỒ UỐNG");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 140, 50));

        jButton8.setText("PHIẾU BÁN HÀNG");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 140, 50));

        jButton9.setText("LOẠI ĐỒ UỐNG");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 140, 50));

        jButton10.setText("NGƯỜI SỬ DỤNG");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 140, 50));

        jButton11.setText("THẺ ĐỊNH DANH");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 140, 50));

        jButton12.setText("DOANH THU");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 140, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\PolyCafe\\src\\main\\resources\\icons\\coffee-shop.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 730, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolyCafeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
